# Generated by Django 2.1.15 on 2020-11-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sitelist_workpending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelist',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitelist',
            name='internal_order',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitelist',
            name='pbl',
            field=models.CharField(max_length=255),
        ),
    ]
