# Generated by Django 2.1.15 on 2020-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201117_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpending',
            name='workorder',
            field=models.CharField(max_length=255),
        ),
    ]
