# Generated by Django 2.1.15 on 2020-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201117_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpending',
            name='completedwork',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workpending',
            name='failure_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workpending',
            name='opended',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workpending',
            name='startwork',
            field=models.DateTimeField(blank=True),
        ),
    ]
