# Generated by Django 2.1.15 on 2020-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201117_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpending',
            name='completedwork',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpending',
            name='opended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpending',
            name='startwork',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
