# Generated by Django 2.1.15 on 2020-11-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201117_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpending',
            name='opended',
            field=models.CharField(max_length=255),
        ),
    ]
