# Generated by Django 2.1.15 on 2020-11-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201117_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpending',
            name='completedwork',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workpending',
            name='opended',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workpending',
            name='startwork',
            field=models.CharField(max_length=255),
        ),
    ]
