# Generated by Django 2.1.15 on 2020-11-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201118_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='WahSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('opended', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('startwork', models.CharField(max_length=255)),
                ('completedwork', models.CharField(max_length=255)),
                ('caller', models.CharField(max_length=255)),
                ('wah_status', models.CharField(max_length=255)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'รายการ Submit WAH',
                'verbose_name_plural': 'รายละเอียดรายการ Submit WAH',
                'db_table': 'wah_submit',
            },
        ),
    ]
