# Generated by Django 2.1.15 on 2020-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_wahsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wahsubmit',
            name='any_ssw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='fls_mame',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='fls_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='fm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='jla_ra',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='management',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='physical',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='planned_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wahsubmit',
            name='type_job',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
