# Generated by Django 2.1.15 on 2020-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201120_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersanalDetaillogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('key_login', models.TextField(blank=True, max_length=6, null=True)),
                ('line_id', models.TextField(blank=True, max_length=255, null=True)),
                ('group_id', models.TextField(blank=True, max_length=255, null=True)),
                ('richmenu_id', models.TextField(blank=True, max_length=255, null=True)),
                ('member_status', models.CharField(blank=True, default='none', max_length=255)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายการพนักงาน',
                'verbose_name_plural': 'รายละเอียดพนักงาน',
                'db_table': 'persanaldetaillogin',
            },
        ),
    ]
