# Generated by Django 2.1.15 on 2020-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_persanaldetaillogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WahSubmitContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('opended', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('startwork', models.CharField(max_length=255)),
                ('completedwork', models.CharField(max_length=255)),
                ('caller', models.CharField(max_length=255)),
                ('wah_status', models.CharField(max_length=255)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
                ('planned_date', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('fls_mame', models.CharField(blank=True, max_length=255)),
                ('fls_phone', models.CharField(blank=True, max_length=255)),
                ('management', models.CharField(blank=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('type_job', models.CharField(blank=True, max_length=255)),
                ('jla_ra', models.CharField(blank=True, max_length=255)),
                ('any_ssw', models.CharField(blank=True, max_length=255)),
                ('physical', models.CharField(blank=True, max_length=255)),
                ('fm', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'รายการ Submit WAH',
                'verbose_name_plural': 'รายละเอียดรายการ Submit WAH',
                'db_table': 'wah_submit',
            },
        ),
        migrations.DeleteModel(
            name='WahSubmit',
        ),
    ]
