# Generated by Django 2.1.15 on 2020-12-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_wahsubmitforcontractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wahsubmitforcontractor',
            name='planned_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
