# Generated by Django 2.1.15 on 2020-12-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201207_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='persanaldetaillogin',
            name='user_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
