# Generated by Django 2.1.15 on 2020-12-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_persanaldetaillogin_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wahsubmitforcontractor',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
