# Generated by Django 2.1.15 on 2020-12-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_wahsubmitforcontractor_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workfromgmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(blank=True, max_length=255, null=True)),
                ('opended', models.CharField(blank=True, max_length=255, null=True)),
                ('caller', models.CharField(blank=True, max_length=255, null=True)),
                ('service_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('problum', models.TextField(blank=True, null=True)),
                ('fm', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'งาน work from gmail ',
                'verbose_name_plural': 'รายละเอียดงาน work from gmail',
                'db_table': 'Workfromgmail',
            },
        ),
        migrations.AlterModelOptions(
            name='workpending',
            options={'verbose_name': 'งาน WAH SUBMIT', 'verbose_name_plural': 'รายละเอียดงาน WAH SUBMIT'},
        ),
    ]
