# Generated by Django 2.1.15 on 2020-12-12 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201211_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfromgmail',
            name='service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workfromgmail',
            name='timestramp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 18, 1, 20, 663600)),
        ),
    ]
