# Generated by Django 2.1.15 on 2020-12-23 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201212_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.CharField(blank=True, max_length=200, null=True)),
                ('type_detail', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'รายการทำงาน',
                'verbose_name_plural': 'รายละเอียดชนิดของงาน',
                'db_table': 'type_of_work',
            },
        ),
        migrations.AlterField(
            model_name='workfromgmail',
            name='timestramp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 14, 33, 49, 681202)),
        ),
    ]
