# Generated by Django 2.1.15 on 2020-12-25 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20201223_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfromgmail',
            name='time_create',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workfromgmail',
            name='timestramp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 57, 32, 831823)),
        ),
    ]
