# Generated by Django 2.1.15 on 2020-12-25 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201225_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfromgmail',
            name='timestramp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 19, 36, 9, 678850)),
        ),
        migrations.AlterField(
            model_name='workfromgmail_new',
            name='time_make',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 19, 36, 9, 679370)),
        ),
    ]
