# Generated by Django 2.1.15 on 2020-12-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20201225_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workfromgmail',
            old_name='date_create',
            new_name='status_submit',
        ),
    ]
