# Generated by Django 2.1.15 on 2020-12-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20201225_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfromgmail',
            name='notify_contractor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
