# Generated by Django 2.1.15 on 2020-12-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_workfromgmail_notify_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfromgmail',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
