# Generated by Django 2.1.15 on 2020-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_workfromgmail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfromgmail',
            name='status_submit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
