# Generated by Django 2.1.15 on 2020-12-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_workfromgmail_completed_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfromgmail',
            name='initials_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
