# Generated by Django 2.1.15 on 2020-12-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_workfromgmail_initials_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wahsubmitforcontractor',
            name='initials_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
